packages:
  - packages/*

catalog:
  '@changesets/cli': ^2.27.1
  '@typescript-eslint/eslint-plugin': ^7.1.0
  '@typescript-eslint/parser': ^7.1.0
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.0.0
  prettier: ^3.2.5
  tshy: ^3.0.2
  turbo: ^2.2.3
  type-fest: ^4.8.3
  typescript: ~5.5.4
